version: '3'
services:
  laravel-app:
    container_name: laravel-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" # Map container's port 80 to host's port 80
    volumes:
      - ./dockerapp:/var/www/html
    depends_on:
      - mysql_db
      - migrate
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dockerapp:/var/www/html
    depends_on:
      - mysql_db
    entrypoint: [ "php", "artisan", "migrate" ]

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: delunoalnueve
      MYSQL_DATABASE: kioskito
